triplot_triplot_homepage:
    pattern:  /app
    defaults: { _controller: TriplotTriplotBundle:Default:index }

triplot_triplot_import:
    pattern:  /import
    defaults: { _controller: TriplotTriplotBundle:Default:import }