parameters:
#    triplot_triplot.example.class: Triplot\TriplotBundle\Example

services:
#    triplot_triplot.example:
#        class: %triplot_triplot.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
