parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: <YOUR DB NAME>
    database_user: <YOUR UsER>
    database_password: <YOUR PASS> 
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: triplot_secret
    database_path: null
